// src/components/common/IconMap.tsx
import * as LucideIcons from "lucide-react";

export const iconMap = {
    'check-square': LucideIcons.CheckSquare,
    'square': LucideIcons.Square,
    'calendar': LucideIcons.CalendarDays,
    'search': LucideIcons.Search,
    'user': LucideIcons.User,
    'settings': LucideIcons.Settings,
    'file-text': LucideIcons.FileText,
    'trash': LucideIcons.Trash2,
    'list': LucideIcons.List,
    'grid': LucideIcons.LayoutGrid,
    'clock': LucideIcons.Clock,
    'alert-circle': LucideIcons.AlertCircle,
    'plus': LucideIcons.Plus,
    'more-horizontal': LucideIcons.MoreHorizontal,
    'chevron-down': LucideIcons.ChevronDown,
    'chevron-up': LucideIcons.ChevronUp,
    'chevron-left': LucideIcons.ChevronLeft,
    'chevron-right': LucideIcons.ChevronRight,
    'sun': LucideIcons.Sun,
    'sunset': LucideIcons.Sunset,
    'history': LucideIcons.History,
    'moon': LucideIcons.Moon,
    'calendar-plus': LucideIcons.CalendarPlus,
    'edit': LucideIcons.Edit3,
    'network': LucideIcons.Network,
    'message-square-text': LucideIcons.MessageSquareText,
    'message-square-plus': LucideIcons.MessageSquarePlus,
    'sticky-note': LucideIcons.StickyNote,
    'file-pen': LucideIcons.FilePen,
    'git-fork': LucideIcons.GitFork,
    'check': LucideIcons.Check,
    'x': LucideIcons.X,
    'arrow-left': LucideIcons.ArrowLeft,
    'arrow-right': LucideIcons.ArrowRight,
    'star': LucideIcons.Star,
    'flag': LucideIcons.Flag,
    'tag': LucideIcons.Tag,
    'bell': LucideIcons.Bell,
    'share': LucideIcons.Share2,
    'upload': LucideIcons.UploadCloud,
    'download': LucideIcons.Download,
    'logout': LucideIcons.LogOut,
    'lock': LucideIcons.Lock,
    'tool': LucideIcons.Wrench,
    'layers': LucideIcons.Layers,
    'package': LucideIcons.Package,
    'sliders': LucideIcons.SlidersHorizontal,
    'info': LucideIcons.Info,
    'help': LucideIcons.HelpCircle,
    'phone': LucideIcons.Phone,
    'slash': LucideIcons.Slash,
    'mail': LucideIcons.Mail,
    'external-link': LucideIcons.ExternalLink,
    'crown': LucideIcons.Crown,
    'terminal': LucideIcons.Terminal,
    'grip-vertical': LucideIcons.GripVertical,
    'copy': LucideIcons.Copy,
    'archive': LucideIcons.Archive,
    'arrow-up-down': LucideIcons.ArrowUpDown,
    'calendar-days': LucideIcons.CalendarDays,
    'loader': LucideIcons.Loader2,
    'users': LucideIcons.Users,
    'sparkles': LucideIcons.Sparkles,
    'folder-plus': LucideIcons.FolderPlus,
    'folder': LucideIcons.Folder,
    'minus': LucideIcons.Minus,
    'inbox': LucideIcons.Inbox,
    'list-checks': LucideIcons.ListChecks,
    'x-circle': LucideIcons.XCircle,
    'key': LucideIcons.Key,
    'calendar-check': LucideIcons.CalendarCheck,
    'refresh-cw': LucideIcons.RefreshCw,
    'copy-plus': LucideIcons.CopyPlus,
    'plus-circle': LucideIcons.PlusCircle,
    'check-circle': LucideIcons.CheckCircle,
    'circle': LucideIcons.Circle,                // For 0% / Not Started
    'circle-dot': LucideIcons.CircleDot,          // For 20%
    'circle-dot-dashed': LucideIcons.CircleDotDashed, // For 50%
    'circle-slash': LucideIcons.CircleSlash,       // For 80%
    'circle-check': LucideIcons.CircleCheckBig,    // For 100%
    'circle-gauge': LucideIcons.GaugeCircle,        // For MetaRow label in TaskDetail
};

export type IconName = keyof typeof iconMap;